{{- if and .Values.notificationPublisher.autoScaling.enabled .Values.notificationPublisher.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hyades.notificationPublisherFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.notificationPublisherLabels" .  | nindent 4 }}
  {{- if .Values.notificationPublisher.autoScaling.annotations }}
  annotations:
  {{- with .Values.notificationPublisher.autoScaling.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hyades.notificationPublisherFullname" . }}
  minReplicas: {{ .Values.notificationPublisher.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.notificationPublisher.autoScaling.maxReplicas }}
  metrics:
    {{- if .Values.notificationPublisher.autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.notificationPublisher.autoScaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.notificationPublisher.autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.notificationPublisher.autoScaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}