{{- if eq (include "dependencytrack.secretManagement.database.kek.chartManaged" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependencytrack.secretManagement.database.kekSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.commonLabels" . | nindent 4 }}
type: Opaque
data:
  {{ include "dependencytrack.secretManagement.database.kekKey" . }}: {{ .Values.secretManagement.database.kek.value | b64enc | quote }}
{{- end }}
