{{- if eq .Values.fileStorage.provider "s3" }}
{{- if .Values.fileStorage.s3.credentials.existingSecret.name }}
{{- if or .Values.fileStorage.s3.credentials.accessKeyId .Values.fileStorage.s3.credentials.secretAccessKey }}
{{- fail "fileStorage.s3.credentials.existingSecret.name is set; remove fileStorage.s3.credentials.accessKeyId and secretAccessKey to avoid ambiguity" }}
{{- end }}
{{- else }}
{{- if or (not .Values.fileStorage.s3.credentials.accessKeyId) (not .Values.fileStorage.s3.credentials.secretAccessKey) }}
{{- fail "fileStorage.s3.credentials.{accessKeyId,secretAccessKey} must be set, or fileStorage.s3.credentials.existingSecret.name must reference an existing Secret" }}
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dependencytrack.s3.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.commonLabels" . | nindent 4 }}
type: Opaque
data:
  accessKeyId: {{ .Values.fileStorage.s3.credentials.accessKeyId | b64enc | quote }}
  secretAccessKey: {{ .Values.fileStorage.s3.credentials.secretAccessKey | b64enc | quote }}
{{- end }}
{{- end }}
