{{- if .Values.frontend.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyades.frontendFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels: {{- include "hyades.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "hyades.frontendSelectorLabels" . | nindent 8 }}
      {{- with .Values.frontend.annotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.common.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      {{- if .Values.frontend.initContainers }}
      {{- toYaml .Values.frontend.initContainers | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "hyades.serviceAccountName" . }}
      containers:
      - name: {{ include "hyades.frontendName" . }}
        image: {{ include "hyades.frontendImage" . }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: false # RO filesystems are not supported by the frontend
          seccompProfile:
            type: RuntimeDefault
        {{- with .Values.frontend.command }}
        command: {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.frontend.args }}
        args: {{ toYaml . | nindent 8 }}
        {{- end }}
        resources: {{- toYaml .Values.frontend.resources | nindent 10 }}
        env:
        - name: API_BASE_URL
          value: {{ .Values.frontend.apiBaseUrl | quote }}
        {{- with .Values.frontend.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.frontend.extraEnvFrom }}
        envFrom: {{ toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- with .Values.frontend.additionalVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /
          failureThreshold: {{ .Values.frontend.probes.liveness.failureThreshold }}
          initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.probes.liveness.periodSeconds }}
          successThreshold: {{ .Values.frontend.probes.liveness.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.probes.liveness.timeoutSeconds }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /
          failureThreshold: {{ .Values.frontend.probes.readiness.failureThreshold }}
          initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.probes.readiness.periodSeconds }}
          successThreshold: {{ .Values.frontend.probes.readiness.successThreshold }}
          timeoutSeconds: {{ .Values.frontend.probes.readiness.timeoutSeconds }}
      {{- with .Values.frontend.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.frontend.additionalVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- end }}