{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dependencytrack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName | empty | not }}
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.hostname | quote }}
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ include "dependencytrack.apiServerFullname" . }}
            port:
              name: web
      - path: /health
        pathType: Prefix
        backend:
          service:
            name: {{ include "dependencytrack.apiServerFullname" . }}
            port:
              name: web
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "dependencytrack.frontendFullname" . }}
            port:
              name: web
{{- end }}
