{{- if .Values.ingress.enabled }}
{{- $apiSvc := include "dependencytrack.apiServer.webFullname" . }}
{{- $rootSvc := ternary (include "dependencytrack.frontend.fullname" .) $apiSvc .Values.frontend.enabled }}
{{- $rootPort := ternary (int .Values.frontend.service.port) (int .Values.apiServer.service.port) .Values.frontend.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dependencytrack.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.ingress.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dependencytrack.commonLabels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $apiSvc }}
                port:
                  name: web
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $rootSvc }}
                port:
                  number: {{ $rootPort }}
{{- end }}
