{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dependencytrack.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.commonLabels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: false
{{- end }}
