{{- if .Values.apiServer.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyades.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.apiServerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels: {{- include "hyades.apiServerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "hyades.apiServerSelectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        {{- with .Values.apiServer.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.common.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      {{- with .Values.apiServer.initContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "hyades.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.apiServer.terminationGracePeriodSeconds }}
      containers:
      - name: {{ include "hyades.apiServerName" . }}
        image: {{ include "hyades.apiServerImage" . }}
        imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        {{- with .Values.apiServer.command }}
        command: {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.apiServer.args }}
        args: {{ toYaml . | nindent 8 }}
        {{- end }}
        resources: {{- toYaml .Values.apiServer.resources | nindent 10 }}
        env:
        - name: ALPINE_METRICS_ENABLED
          value: "true"
        {{- if (include "hyades.secretKeySecretName" .) }}
        - name: ALPINE_SECRET_KEY_PATH
          value: "/var/run/secrets/secret.key"
        {{- end }}
        - name: ALPINE_DATABASE_MODE
          value: "external"
        - name: ALPINE_DATABASE_DRIVER
          value: "org.postgresql.Driver"
        {{- with .Values.common.database.jdbcUrl }}
        - name: ALPINE_DATABASE_URL
          value: {{ tpl . $ | quote }}
        {{- end}}
        {{- with .Values.common.database.username }}
        - name: ALPINE_DATABASE_USERNAME
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.common.database.password }}
        - name: ALPINE_DATABASE_PASSWORD
          value: {{ . | quote }}
        {{- end }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ tpl .Values.common.kafka.bootstrapServers $ | quote }}
        {{- with .Values.common.kafka.topicPrefix }}
        - name: KAFKA_TOPIC_PREFIX
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.apiServer.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.apiServer.extraEnvFrom }}
        envFrom: {{ toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        {{- if (include "hyades.secretKeySecretName" .) }}
        - name: secret-key
          subPath: secret.key
          mountPath: /var/run/secrets/secret.key
          readOnly: true
        {{- end }}
        {{- with .Values.apiServer.additionalVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /health/live
          failureThreshold: {{ .Values.apiServer.probes.liveness.failureThreshold }}
          initialDelaySeconds: {{ .Values.apiServer.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiServer.probes.liveness.periodSeconds }}
          successThreshold: {{ .Values.apiServer.probes.liveness.successThreshold }}
          timeoutSeconds: {{ .Values.apiServer.probes.liveness.timeoutSeconds }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /health/ready
          failureThreshold: {{ .Values.apiServer.probes.readiness.failureThreshold }}
          initialDelaySeconds: {{ .Values.apiServer.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiServer.probes.readiness.periodSeconds }}
          successThreshold: {{ .Values.apiServer.probes.readiness.successThreshold }}
          timeoutSeconds: {{ .Values.apiServer.probes.readiness.timeoutSeconds }}
      {{- with .Values.apiServer.extraContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.apiServer.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: data
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      {{- with (include "hyades.secretKeySecretName" .) }}
      - name: secret-key
        secret:
          secretName: {{ . }}
      {{- end }}
      {{- with .Values.apiServer.additionalVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}