{{- if and .Values.apiServer.autoScaling.enabled .Values.apiServer.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hyades.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.apiServerLabels" . | nindent 4 }}
  {{- if .Values.apiServer.autoScaling.annotations }}
  annotations:
  {{- with .Values.apiServer.autoScaling.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hyades.apiServerFullname" . }}
  minReplicas: {{ .Values.apiServer.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.apiServer.autoScaling.maxReplicas }}
  metrics:
    {{- if .Values.apiServer.autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiServer.autoScaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.apiServer.autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.apiServer.autoScaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}