{{- if .Values.apiServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyades.apiServerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.apiServerLabels" . | nindent 4 }}
  {{- with .Values.apiServer.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.apiServer.service.type | quote }}
  ports:
  - name: web
    port: {{ .Values.apiServer.service.port }}
    targetPort: web
    {{- with .Values.apiServer.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector: {{- include "hyades.apiServerSelectorLabels" . | nindent 4 }}
{{- end }}
