apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hyades.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.apiServer.ingress.hostname | quote }}
    http:
      paths:
        - path: /
          backend:
            serviceName: postgres-container
            servicePort: 5432
