{{- if .Values.common.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hyades.serviceAccountName" . }}
  labels: {{- include "hyades.commonLabels" . | nindent 4 }}
  annotations: {{- toYaml .Values.common.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ .Values.common.serviceAccount.automount }}
{{- end }}