{{- $topology := include "dependencytrack.topology" . }}
{{- $role := ternary "web" "monolith" (eq $topology "split") }}
{{- $envFrom := concat .Values.apiServer.extraEnvFrom .Values.apiServer.web.extraEnvFrom -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dependencytrack.apiServer.webFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.componentLabels" (dict "ctx" . "component" "api-server" "role" "web") | nindent 4 }}
  {{- with .Values.apiServer.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.apiServer.web.autoscaling.enabled }}
  replicas: {{ .Values.apiServer.web.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.apiServer.web.revisionHistoryLimit }}
  strategy: {{- toYaml .Values.apiServer.deployment.strategy | nindent 4 }}
  selector:
    matchLabels: {{- include "dependencytrack.selectorLabels" (dict "ctx" . "component" "api-server" "role" "web") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dependencytrack.selectorLabels" (dict "ctx" . "component" "api-server" "role" "web") | nindent 8 }}
        {{- with .Values.apiServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.apiServer.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "dependencytrack.serviceAccountName" . }}
      automountServiceAccountToken: false
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      terminationGracePeriodSeconds: {{ .Values.apiServer.web.terminationGracePeriodSeconds }}
      {{- with .Values.apiServer.web.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.apiServer.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.initContainers }}
      initContainers:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: api-server
          image: {{ include "dependencytrack.apiServer.image" . }}
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          {{- with .Values.apiServer.securityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.command }}
          command: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.args }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.apiServer.web.resources | nindent 12 }}
          env:
            {{- include "dependencytrack.podEnv" (dict "ctx" . "role" $role) | nindent 12 }}
          {{- with $envFrom }}
          envFrom: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: {{ .Values.apiServer.service.managementPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: management
              path: /health/live
            {{- toYaml .Values.apiServer.probes.liveness | nindent 12 }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: management
              path: /health/ready
            {{- toYaml .Values.apiServer.probes.readiness | nindent 12 }}
          startupProbe:
            httpGet:
              scheme: HTTP
              port: management
              path: /health/started
            {{- toYaml .Values.apiServer.probes.startup | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            {{- include "dependencytrack.secretVolumeMounts" (dict "ctx" . "includeFileStorage" true) | nindent 12 }}
            {{- include "dependencytrack.fileStorage.volumeMounts" . | nindent 12 }}
            {{- with .Values.apiServer.additionalVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- with .Values.apiServer.extraContainers }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- include "dependencytrack.secretVolumes" (dict "ctx" . "includeFileStorage" true) | nindent 8 }}
        {{- include "dependencytrack.fileStorage.volumes" . | nindent 8 }}
        {{- with .Values.apiServer.additionalVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.apiServer.web.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.web.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.web.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.web.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
