common:
  secretKey:
    createSecret: true

apiServer:
  resources:
    requests:
      cpu: "1"
      memory: "512Mi"
    limits:
      cpu: "2"
      memory: "512Mi"
  extraEnv:
    - name: SYSTEM_REQUIREMENT_CHECK_ENABLED
      value: "false"
  initContainers:
    - name: fix-permissions
      image: docker.io/library/busybox
      command:
        - sh
        - -c
        - |
          chown -R 1000:1000 /data
      volumeMounts:
        - name: data
          mountPath: /data
      securityContext:
        capabilities:
          add:
          - CHOWN
        runAsNonRoot: false
        runAsUser: 0
        seccompProfile:
          type: RuntimeDefault
