{{- if .Values.frontend.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dependencytrack.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dependencytrack.componentLabels" (dict "ctx" . "component" "frontend" "role" "") | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - name: web
      port: {{ .Values.frontend.service.port }}
      targetPort: web
      protocol: TCP
      {{- if not (kindIs "invalid" .Values.frontend.service.nodePort) }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector: {{- include "dependencytrack.selectorLabels" (dict "ctx" . "component" "frontend" "role" "") | nindent 4 }}
{{- end }}
