{{- if and .Values.initializer.enabled .Values.initializer.waiter.createRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hyades.initializerWaiterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "hyades.initializerWaiterFullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "hyades.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}