{{- if and .Values.initializer.enabled .Values.initializer.waiter.createRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "hyades.initializerWaiterFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.commonLabels" . | nindent 4 }}
rules:
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
{{- end }}