apiVersion: v2
name: hyades
version: 0.25.0
type: application
appVersion: 5.0.3
deprecated: true
description: |-
  DEPRECATED: hyades was the preview chart for Dependency-Track v5.
  It is discontinued in favor of version 2 of the `dependency-track` chart.

  Migration guide:
  https://github.com/DependencyTrack/helm-charts/blob/main/charts/dependency-track/UPGRADING.md
home: https://dependencytrack.github.io/docs/next
sources:
- https://github.com/DependencyTrack/helm-charts/tree/main/charts/hyades
- https://github.com/DependencyTrack/hyades-apiserver
- https://github.com/DependencyTrack/hyades-frontend
icon: https://avatars.githubusercontent.com/u/40258585
