apiVersion: v2
name: hyades
version: 0.14.0
type: application
appVersion: 0.7.0-alpha.4
description: |-
  Hyades is the next major version of OWASP Dependency-Track.
  It has not yet reached GA. For a production-ready release, use the `dependency-track` chart.
  Before upgrading, please consult the [upgrade guides](https://dependencytrack.github.io/docs/next/guides/upgrading/).
home: https://dependencytrack.github.io/docs/next
sources:
- https://github.com/DependencyTrack/helm-charts/tree/main/charts/hyades
- https://github.com/DependencyTrack/hyades-apiserver
- https://github.com/DependencyTrack/hyades-frontend
icon: https://avatars.githubusercontent.com/u/40258585
maintainers:
- name: nscuro
  email: nscuro@protonmail.com
  url: https://github.com/nscuro
- name: mehab
  email: meha.bhargava@citi.com
  url: https://github.com/mehab
- name: sahibamittal
  email: sahiba.mittal@citi.com
  url: https://github.com/sahibamittal
- name: VithikaS
  email: vithika.shukla@citi.com
  url: https://github.com/VithikaS
