---
common:
  database:
    jdbcUrl: "jdbc:postgresql://host.minikube.internal:5432/dtrack"
    username: "dtrack"
    password: "dtrack"
  kafka:
    bootstrapServers: "host.minikube.internal:9093"
  secretKey:
    createSecret: true

apiServer:
  resources:
    requests:
      cpu: "2"
      memory: 1Gi
    limits:
      cpu: "4"
      memory: 2Gi
  service:
    type: NodePort
    nodePort: 30080
  extraEnv:
  - name: EXTRA_JAVA_OPTIONS
    value: "-Xmx2g"

frontend:
  service:
    type: NodePort
    nodePort: 30081
  apiBaseUrl: "http://localhost:30080"
