{{- if and .Values.vulnAnalyzer.enabled (not .Values.vulnAnalyzer.useStatefulSet) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyades.vulnAnalyzerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.vulnAnalyzerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.vulnAnalyzer.replicaCount }}
  selector:
    matchLabels: {{- include "hyades.vulnAnalyzerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "hyades.vulnAnalyzerSelectorLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        {{- with .Values.vulnAnalyzer.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.common.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      {{- with .Values.notificationPublisher.initContainers }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "hyades.serviceAccountName" . }}
      containers:
      - name: {{ include "hyades.vulnAnalyzerName" . }}
        image: {{ include "hyades.vulnAnalyzerImage" . }}
        imagePullPolicy: {{ .Values.vulnAnalyzer.image.pullPolicy }}
        securityContext: {{ toYaml .Values.vulnAnalyzer.securityContext | nindent 10 }}
        {{- with .Values.vulnAnalyzer.command }}
        command: {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.vulnAnalyzer.args }}
        args: {{ toYaml . | nindent 8 }}
        {{- end }}
        resources: {{- toYaml .Values.vulnAnalyzer.resources | nindent 10 }}
        env:
        {{- with .Values.common.database.jdbcUrl }}
        - name: QUARKUS_DATASOURCE_JDBC_URL
          value: {{ tpl . $ | quote }}
        {{- end}}
        {{- with .Values.common.database.username }}
        - name: QUARKUS_DATASOURCE_USERNAME
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.common.database.password }}
        - name: QUARKUS_DATASOURCE_PASSWORD
          value: {{ . | quote }}
        {{- end }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ tpl .Values.common.kafka.bootstrapServers $ | quote }}
        {{- with .Values.common.kafka.topicPrefix }}
        - name: DT_KAFKA_TOPIC_PREFIX
          value: {{ . | quote }}
        {{- end }}
        {{- with .Values.vulnAnalyzer.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.vulnAnalyzer.extraEnvFrom }}
        envFrom: {{ toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: web
          containerPort: 8092
          protocol: TCP
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- with .Values.vulnAnalyzer.additionalVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /q/health/live
          failureThreshold: {{ .Values.vulnAnalyzer.probes.liveness.failureThreshold }}
          initialDelaySeconds: {{ .Values.vulnAnalyzer.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.vulnAnalyzer.probes.liveness.periodSeconds }}
          successThreshold: {{ .Values.vulnAnalyzer.probes.liveness.successThreshold }}
          timeoutSeconds: {{ .Values.vulnAnalyzer.probes.liveness.timeoutSeconds }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: web
            path: /q/health/ready
          failureThreshold: {{ .Values.vulnAnalyzer.probes.readiness.failureThreshold }}
          initialDelaySeconds: {{ .Values.vulnAnalyzer.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.vulnAnalyzer.probes.readiness.periodSeconds }}
          successThreshold: {{ .Values.vulnAnalyzer.probes.readiness.successThreshold }}
          timeoutSeconds: {{ .Values.vulnAnalyzer.probes.readiness.timeoutSeconds }}
      {{- with .Values.vulnAnalyzer.extraContainers }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
      {{- with .Values.vulnAnalyzer.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vulnAnalyzer.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.vulnAnalyzer.additionalVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}