{{- if and .Values.vulnAnalyzer.autoScaling.enabled .Values.vulnAnalyzer.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hyades.vulnAnalyzerFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.vulnAnalyzerLabels" . | nindent 4 }}
  {{- if .Values.vulnAnalyzer.autoScaling.annotations }}
  annotations:
  {{- with .Values.vulnAnalyzer.autoScaling.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    {{- if .Values.vulnAnalyzer.useStatefulSet }}
    kind: StatefulSet
    {{- else }}
    kind: Deployment
    {{- end }}
    name: {{ include "hyades.vulnAnalyzerFullname" . }}
  minReplicas: {{ .Values.vulnAnalyzer.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.vulnAnalyzer.autoScaling.maxReplicas }}
  metrics:
    {{- if .Values.vulnAnalyzer.autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.vulnAnalyzer.autoScaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.vulnAnalyzer.autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.vulnAnalyzer.autoScaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}