{{- if and .Values.vulnAnalyzer.enabled .Values.vulnAnalyzer.useStatefulSet }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyades.vulnAnalyzerFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.vulnAnalyzerLabels" . | nindent 4 }}
  {{- with .Values.vulnAnalyzer.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: web
  selector: {{- include "hyades.vulnAnalyzerSelectorLabels" . | nindent 4 }}
{{- end }}