{{- if .Values.vulnAnalyzer.enabled }}
{{/*
TODO: The headless service is only required when vulnAnalyzer is a StatefulSet.
  Make this conditional when implementing https://github.com/DependencyTrack/helm-charts/issues/90
*/}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyades.vulnAnalyzerFullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels: {{- include "hyades.vulnAnalyzerLabels" . | nindent 4 }}
  {{- with .Values.vulnAnalyzer.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: web
  selector: {{- include "hyades.vulnAnalyzerSelectorLabels" . | nindent 4 }}
{{- end }}